common: &common
  adapter: postgresql
  encoding: utf8
  pool: 5
  username: angular
  password: password

test:
  <<: *common
  database: angular_devise_test

development:
  <<: *common
  database: angular_devise_development

production:
  <<: *common
  database: angular_devise_production